language: node_js
node_js:
  - '15'
jdk:
  - openjdk11
dist: trusty
sudo: required
branches:
  only:
  - release
  - develop
  - "/feature\\//"
addons:
  chrome: stable
  sonarcloud:
    organization: "processpuzzle"
    token:
      secure: "C7Y9ISFLwCDf0if6E7EYzcclginqXJpeAmwQylYQ/roDnU67m6t2lLxHPlMrpHVieEU3Rlt5FtuANpcO7o7DGkA3mkMYN4L32gxpCvAGUXrb1Zr3Sh0pJ7wK4LFXd6wdWrDQ8qJc/OPABie0WBwWbDgXuAftX+YRsazTysSinggCBkpUw92GseRYfqVItbw85hWlpMPGpGJ06OcOVX28jmJVrhZM8z8i0Wr8C5jtzc6MeM0A4LxGHSRdXkHPCleXBHo3zKT9w+Uwbhm2dVD0NS+GdZ8zT1eshwfd3oAuqKpQXW4YuoHhYO6Nn3cmIc17MrrxqQPe3DLk/RO6zZlNQkK9fO/vB+YiBTwCPJjYIRFBxcfXlwXdd4J1HqMncobCBmnzSC5nu21Sz3fnh+31lDxRObPMwqG+dQWCaPKW48DFbXSPHBLfYFclvDufOnahwUC9d16Ih6pR9CLytV1JGZlV8w9HV6l3OFpXMR3S4Hl4XxU9cb8ZjikhD8mA4+YLPzFqcV/vegQ3us+ADLUiWd1TZpXX8x1IKjzrD1fuyMj9/dEf7JVi1XvlkMznzE2cqw5r08phzIZWYxkHhN+tuKyzO1uNuvKNN82rZwBoj36WJiTWpmbbwD9Whd2ImPvLEk+rqBrGydKK7pfCcDsh/Gy8hLH6ie1jmnFWbDQwoCU="
    branches:
    - develop
    - release
    - "/feature\\//"
cache:
  directories:
  - "$HOME/.sonar/cache"
  - "./node_modules"
before_script:
- npm install -g --silent @angular/cli
script:
- npm install
- ng lint
- sonar-scanner
- ng build --base-href https://test.sailrc.de/
deploy:
  skip_cleanup: true
  provider: firebase
  project: sailrc-test
  on:
    branch: develop
  token:
    secure: "VVUNLJ6jqIsJj2A7+QRxwmGuBAnpmlYW1w3t/naMTE6cQBVVFEieTgeBWxzDx1g0i/fTHat9rbL/wzxg8bp/PN5BJbSegwD82a4P7D28ApGlYTMrbNyMqzr52SIVgNBsZPvy7x1nUVxQnq5U0rmsL2uDFTsEu0bVuQ7YNl1XG8eZGPaZS/+Vnx2Ok1+zsxW+sUaGxF6ZVLt1RgYP5CYIzc4hEdZbv+yGHIBIsG8VI+AEHds24/mNXm28oPwec/HDPRd2RsHiZlY0X9CnR5ByvLHN2v3SyfmFF1B0Dig0eowCtVhAIEdYgqsGJ/CFuKRFO7S7PdMxv1FjUpUcXQqvC7wkWCBe2OKQ+xVUNm+oMbugC/Kl9XZ5Kvm5V3OQlW4aCthj32++bwq8V5S38JIuBbK6xqj2A5W0VZNHgUsJwMJd3xMnWOeRkWJM0iTg9cQAuTGDtwh/z0zK0NV0jxf+1++lowJybDilAJWhOOyEbxXANAY+LvIVExLy9aPH30dSQoJxoBlAi+wFvWr9ruqoDQqhXtxkZTr7soczAuk2ItyNvfVBuvhyD9+AbyGC8EFhVMcKf3P3x+nUa2rQv8chnVODiaGTdPh6PPDCVo7EkxiSyeJ8K4rlj3yogsoPw5Df6xNfdVXG7fMuiKj2b1RQk7Q/XO19/fLX5rqRBXOz3/0="
env:
  global:
    secure: C7Y9ISFLwCDf0if6E7EYzcclginqXJpeAmwQylYQ/roDnU67m6t2lLxHPlMrpHVieEU3Rlt5FtuANpcO7o7DGkA3mkMYN4L32gxpCvAGUXrb1Zr3Sh0pJ7wK4LFXd6wdWrDQ8qJc/OPABie0WBwWbDgXuAftX+YRsazTysSinggCBkpUw92GseRYfqVItbw85hWlpMPGpGJ06OcOVX28jmJVrhZM8z8i0Wr8C5jtzc6MeM0A4LxGHSRdXkHPCleXBHo3zKT9w+Uwbhm2dVD0NS+GdZ8zT1eshwfd3oAuqKpQXW4YuoHhYO6Nn3cmIc17MrrxqQPe3DLk/RO6zZlNQkK9fO/vB+YiBTwCPJjYIRFBxcfXlwXdd4J1HqMncobCBmnzSC5nu21Sz3fnh+31lDxRObPMwqG+dQWCaPKW48DFbXSPHBLfYFclvDufOnahwUC9d16Ih6pR9CLytV1JGZlV8w9HV6l3OFpXMR3S4Hl4XxU9cb8ZjikhD8mA4+YLPzFqcV/vegQ3us+ADLUiWd1TZpXX8x1IKjzrD1fuyMj9/dEf7JVi1XvlkMznzE2cqw5r08phzIZWYxkHhN+tuKyzO1uNuvKNN82rZwBoj36WJiTWpmbbwD9Whd2ImPvLEk+rqBrGydKK7pfCcDsh/Gy8hLH6ie1jmnFWbDQwoCU=
