language: node_js
node_js:
- '15'
dist: trusty
sudo: required
branches:
  only:
  - release
  - develop
  - "/feature\\//"
addons:
  chrome: stable
  sonarcloud:
    organization: processpuzzle
    token:
      secure: "$SONAR_TOKEN"
    branches:
    - development
    - release
    - "/feature\\//"
cache:
  directories:
  - "$HOME/.sonar/cache"
  - "./node_modules"
before_script:
- npm install -g --silent @angular/cli
- npm run config-env --environment=prod
script:
- npm install
- ng lint
- sonar-scanner
- ng build --base-href https://test.sailrc.de/
deploy:
  skip_cleanup: true
  provider: firebase
  project: sailrc-test
  on:
    branch: develop
  token:
    secure: OWogt+FrlxZfQcSOC6sDyPrPRhiyOy96zuObgkw5iRrbNERTj6av0vcDVqFkrXl9LimJqaT1fNwdqOT9RNnaPJK0P8ghmQjJXPk5ezrNnI7ECRB9qZv4ofIBTlqt7/VMaB4C3WWkWLWs8PZ0bIUvgN8TC/uRFvOM5oUzhRFRfUa/3mh9sxHpHiMOFr3N24V/+68PWpu5lJTcDiDHkVAXWPw/DmpLvKYDtstkRD37yqZNd4sryp8xtHeGcQFA1NTFb7wQ0wNjESiNVw+9EKfxJEBxfyQZ8RPrfccT5SuCtABuvEPctIWd550YuQEQU/bPmvQqh6vfWASYIWck1AdWiJBDuUS6ubHcE7LSHTFL8GEOoiU3s4NOGNO2IU0HxXrdYwX8Zi2s6CJ/FAsyYAffq6ggIN9f1mqba4PI9+4Nv6evXZWnAvUYJe23vJMiBBLJyqCOJnCHTP5NI73lxiT7fOfxxE8ai95g/XNI3Af+QbbKJRCxLF8IMR8Cml89TPIiabs6rRuk7XhYkSzBeXFz9FnVPGw82pwKc2W8+04cSlXbDUMlXy9FedFzxeLvpP1L2Z1hnuWRjn5MW/5YFUuD7ZtxGm1ct14uJv/aJ16BqbPACZ0E54kgVcrUdZyceSX8d2xKS1CfkJQZUBnFsG2oTf6XQJsYyYRGBx4G9f/fB+Y=
