language: node_js
node_js:
- '15'
dist: xenial
sudo: required
branches:
  only:
  - release
  - develop
  - "/feature\\//"
  - "/hotfix\\//"
addons:
  chrome: stable
  sonarcloud:
    organization: processpuzzle
    token:
      secure: C7Y9ISFLwCDf0if6E7EYzcclginqXJpeAmwQylYQ/roDnU67m6t2lLxHPlMrpHVieEU3Rlt5FtuANpcO7o7DGkA3mkMYN4L32gxpCvAGUXrb1Zr3Sh0pJ7wK4LFXd6wdWrDQ8qJc/OPABie0WBwWbDgXuAftX+YRsazTysSinggCBkpUw92GseRYfqVItbw85hWlpMPGpGJ06OcOVX28jmJVrhZM8z8i0Wr8C5jtzc6MeM0A4LxGHSRdXkHPCleXBHo3zKT9w+Uwbhm2dVD0NS+GdZ8zT1eshwfd3oAuqKpQXW4YuoHhYO6Nn3cmIc17MrrxqQPe3DLk/RO6zZlNQkK9fO/vB+YiBTwCPJjYIRFBxcfXlwXdd4J1HqMncobCBmnzSC5nu21Sz3fnh+31lDxRObPMwqG+dQWCaPKW48DFbXSPHBLfYFclvDufOnahwUC9d16Ih6pR9CLytV1JGZlV8w9HV6l3OFpXMR3S4Hl4XxU9cb8ZjikhD8mA4+YLPzFqcV/vegQ3us+ADLUiWd1TZpXX8x1IKjzrD1fuyMj9/dEf7JVi1XvlkMznzE2cqw5r08phzIZWYxkHhN+tuKyzO1uNuvKNN82rZwBoj36WJiTWpmbbwD9Whd2ImPvLEk+rqBrGydKK7pfCcDsh/Gy8hLH6ie1jmnFWbDQwoCU=
    branches:
    - develop
    - release
    - "/feature\\//"
    - "/hotfix\\//"
cache:
  directories:
  - "$HOME/.sonar/cache"
  - "./node_modules"
git:
  depth: false
before_script:
- npm install -g --silent @angular/cli
- npm run config-env --environment=prod
script:
- npm install
- ng lint
- npm run test
- sonar-scanner
- npm run build-test
deploy:
  skip_cleanup: true
  provider: firebase
  project: sailrc-test
  on:
    branch: develop
  token:
    secure: VVUNLJ6jqIsJj2A7+QRxwmGuBAnpmlYW1w3t/naMTE6cQBVVFEieTgeBWxzDx1g0i/fTHat9rbL/wzxg8bp/PN5BJbSegwD82a4P7D28ApGlYTMrbNyMqzr52SIVgNBsZPvy7x1nUVxQnq5U0rmsL2uDFTsEu0bVuQ7YNl1XG8eZGPaZS/+Vnx2Ok1+zsxW+sUaGxF6ZVLt1RgYP5CYIzc4hEdZbv+yGHIBIsG8VI+AEHds24/mNXm28oPwec/HDPRd2RsHiZlY0X9CnR5ByvLHN2v3SyfmFF1B0Dig0eowCtVhAIEdYgqsGJ/CFuKRFO7S7PdMxv1FjUpUcXQqvC7wkWCBe2OKQ+xVUNm+oMbugC/Kl9XZ5Kvm5V3OQlW4aCthj32++bwq8V5S38JIuBbK6xqj2A5W0VZNHgUsJwMJd3xMnWOeRkWJM0iTg9cQAuTGDtwh/z0zK0NV0jxf+1++lowJybDilAJWhOOyEbxXANAY+LvIVExLy9aPH30dSQoJxoBlAi+wFvWr9ruqoDQqhXtxkZTr7soczAuk2ItyNvfVBuvhyD9+AbyGC8EFhVMcKf3P3x+nUa2rQv8chnVODiaGTdPh6PPDCVo7EkxiSyeJ8K4rlj3yogsoPw5Df6xNfdVXG7fMuiKj2b1RQk7Q/XO19/fLX5rqRBXOz3/0=
env:
  global:
  - secure: C7Y9ISFLwCDf0if6E7EYzcclginqXJpeAmwQylYQ/roDnU67m6t2lLxHPlMrpHVieEU3Rlt5FtuANpcO7o7DGkA3mkMYN4L32gxpCvAGUXrb1Zr3Sh0pJ7wK4LFXd6wdWrDQ8qJc/OPABie0WBwWbDgXuAftX+YRsazTysSinggCBkpUw92GseRYfqVItbw85hWlpMPGpGJ06OcOVX28jmJVrhZM8z8i0Wr8C5jtzc6MeM0A4LxGHSRdXkHPCleXBHo3zKT9w+Uwbhm2dVD0NS+GdZ8zT1eshwfd3oAuqKpQXW4YuoHhYO6Nn3cmIc17MrrxqQPe3DLk/RO6zZlNQkK9fO/vB+YiBTwCPJjYIRFBxcfXlwXdd4J1HqMncobCBmnzSC5nu21Sz3fnh+31lDxRObPMwqG+dQWCaPKW48DFbXSPHBLfYFclvDufOnahwUC9d16Ih6pR9CLytV1JGZlV8w9HV6l3OFpXMR3S4Hl4XxU9cb8ZjikhD8mA4+YLPzFqcV/vegQ3us+ADLUiWd1TZpXX8x1IKjzrD1fuyMj9/dEf7JVi1XvlkMznzE2cqw5r08phzIZWYxkHhN+tuKyzO1uNuvKNN82rZwBoj36WJiTWpmbbwD9Whd2ImPvLEk+rqBrGydKK7pfCcDsh/Gy8hLH6ie1jmnFWbDQwoCU=
  - secure: rgWbaXoZ9c5dIdr25jFQFjPHGu0fShEkH1lm+KO9WvYQ4jtWBo+BfNnOkZGAiZuYSupDxJIgulfP+RA/ZAXe/YiUNbOn7W7zEo8LLB/rKJJKjPU4GaQYJl+6ytAhvPeMZDvZj/7t+LSMUdHDr/2Td6DQeFF2CjTVUr6EE6mg01Tk0N/9Li749TSwVr58Lw/5qp/Txzs11gH3lqS5y6zknS/7DPMZuP+F8uwInIbulqartufCeoGz7JhZH9rHzovcclh1D4U8wVcn6jeyr2WheEBafC2EFwpR3linK+EOWjtVEtom/qnjFHsTgCPbKKCnGv0ZAwESOqrXE+oD8P1fJ7Qs+Q+U2AF/8VQwwPTMlBFwHgh5n+dZI7zoXfCu9oHPxYdpH7nIq8uM28ebNWcvOV8qY9ipgaOd9jarOeb0srHs/isrhlbE9Jr5uAm0LphADCDCOUDIhx5jfPKuDwGQAX/UY5Yyhx2LJMZhWUhsmeeQNy1LrN23jetXEFnBDBhLXdv7+cDQw6069LBJewY1JtqyzCp6KvwJfl5dZ6A3qAU6rPH7XR7XFH/glCQYAOAGh9vFsl5GLgHQCj6ltuZf86F/HvPHMMFr+JG4mmWIh57GkIHrNA+QNTglkxd/sQaGKQaadcKOXg7txhNyGpkDwL9Ch4JSD8xJR8cPtffyrPs=
  - secure: lrZARBbNVECfYGzPEan2YGg+qbDmw8ACsUxipjVs3juDjnVu4csiKHjcokG5Zd06YsQuOdzRAX9yvlbfsbFt4VikBv2a65PgJPtEfnckIY0IfOqI8POfzNDm0ZhFfBV9QWo0v0ExpucaWO+Kq7keQ3dNCIhDf5cYhxes+DBNWcaoSEfic+Q+oCGH90+aFVryDpStATsOC4I5Gp9UGzNtbSL3LZTRt+p1MlgGrEfIhgLQv5fv53BWQxFLvk10V7AAaicBEl/RfnW+zZ3TDS9b1F8Ss3ycGhkEVU7nplqj3gU5hZBDCjCYDptCr+sCQbL92H4uf26dBDOYDMOA7AaUYoDvmdsGdTLLZVYYWW/ekzpAoMtUVWtP3ct8mEUC+4EHsbw5/D+RDWjF2V4xkUYpKLY7gwJ0zoTsBduavcQcjhecB6FqG8VgHvuiUpFrCElAbJUTeiQKmDkeQ7VpCrADHf5pF1W16MD8bV08jJEeY+esJIw06ba0Jo5AOvwChIX2GvLnV94waC6AWFp2maqMBqA/cKMvV1WhFS3dpydPO7BKvUSwve2zZx9S0r5ky/djJJsf3ZQCDgwPMIBwsgFGeXCBwVL1AtBaF2N3TB69rS716UszORDRUw+UHt+rVVvy2Y8VjQC5/bzfNXDlh+KsN1F96zBzbSQJAmoHM9jFYFY=
