
module.exports = {
  preset: 'jest-preset-angular',
  setupFilesAfterEnv: ['<rootDir>/setup-jest.ts'],
  globalSetup: 'jest-preset-angular/global-setup',
  collectCoverage: true,
  coverageReporters: ['html', 'json', 'text', 'cobertura', ['lcov', { projectRoot: '/' }]],
  reporters: ['default', 'jest-junit'],
  testPathIgnorePatterns: ['<rootDir>/src/environments', '<rootDir>/src/assets'],
  coveragePathIgnorePatterns: ['node_modules', 'test-config', 'interfaces', 'jestGlobalMocks.ts', '.module.ts', '<rootDir>/src/app/main.ts', '.mock.ts', 'index.ts'],
  snapshotSerializers: [
    'jest-preset-angular/build/serializers/no-ng-attributes.js',
    'jest-preset-angular/build/serializers/ng-snapshot.js',
    'jest-preset-angular/build/serializers/html-comment.js',
  ],
  projects: [
    '<rootDir>/apps/sail-rc',
    '<rootDir>/libs/boat/domain',
    '<rootDir>/libs/boat/feature',
    '<rootDir>/libs/boat-class/domain',
    '<rootDir>/libs/boat-class/feature',
    '<rootDir>/libs/race/feature',
    '<rootDir>/libs/race/field',
    '<rootDir>/libs/race/finish',
    '<rootDir>/libs/race/domain',
    '<rootDir>/libs/race/participant',
    '<rootDir>/libs/race/shared',
    '<rootDir>/libs/race/start',
    '<rootDir>/libs/sailor/domain',
    '<rootDir>/libs/sailor/feature',
    '<rootDir>/libs/sailing-place/domain',
    '<rootDir>/libs/sailing-place/feature',
    '<rootDir>/libs/shared/authentication/domain',
    '<rootDir>/libs/shared/authentication/feature',
    '<rootDir>/libs/shared/base',
    '<rootDir>/libs/shared/base/base',
    '<rootDir>/libs/shared/material',
    '<rootDir>/libs/shared/test-util',
    '<rootDir>/libs/shared/util',
    '<rootDir>/libs/shared/widgets',
    '<rootDir>/libs/yacht-club/domain',
    '<rootDir>/libs/yacht-club/feature',
  ],
};
